const places = [
  {
    id: 1,
    name: "Dubai",
    duration: "2-3 days",
    rating: "3.8",
    image: "https://res.cloudinary.com/codiini/image/upload/v1616659084/dubai_jcwgcz.jpg",
  },
  {
    id: 2,
    name: "Las Vegas",
    duration: "10 days",
    rating: "3.5",
    image: "https://res.cloudinary.com/codiini/image/upload/v1616659068/las-vegas_nlrqhn.jpg",
  },
  {
    id: 3,
    name: "New York",
    duration: "3-8 days",
    rating: "3.2",
    image: "https://res.cloudinary.com/codiini/image/upload/v1616666338/new-york_srtrme.jpg",
  },
  {
    id: 4,
    name: "Tokyo",
    duration: "2-3 days",
    rating: "4.0",
    image: "https://res.cloudinary.com/codiini/image/upload/v1616659068/tokyo_ejm9kl.jpg",
  },
  {
    id: 5,
    name: "Santorini",
    duration: "5-8 days",
    rating: "4.2",
    image: "https://res.cloudinary.com/codiini/image/upload/v1616659056/santorini_zlmwqh.jpg",
  },
  {
    id: 6,
    name: "Maldives",
    duration: "8-10 days",
    rating: "4.5",
    image: "https://res.cloudinary.com/codiini/image/upload/v1616666326/maldives_mypvym.jpg",
  },
  {
    id: 7,
    name: "Japan",
    duration: "5-10 days",
    rating: "3.8",
    image: "https://res.cloudinary.com/codiini/image/upload/v1616666427/japan_nkljfl.jpg",
  },
  {
    id: 8,
    name: "Berlin",
    duration: "9-15 days",
    rating: "4.3",
    image: "https://res.cloudinary.com/codiini/image/upload/v1616666453/berlin_vgroji.jpg",
  },
  {
    id: 9,
    name: "Malibu",
    duration: "2-8 days",
    rating: "4.2",
    image: "https://res.cloudinary.com/codiini/image/upload/v1616666326/malibu_bd7ycs.jpg",
  },
  {
    id: 10,
    name: "Rwanda",
    duration: "5-8 days",
    rating: "4.4",
    image: "https://res.cloudinary.com/codiini/image/upload/v1616666370/rwanda_qmc7yp.jpg",
  },
  {
    id: 11,
    name: "Egypt",
    duration: "5-8 days",
    rating: "3.6",
    image: "https://res.cloudinary.com/codiini/image/upload/v1616666404/egypt_vxj1tb.jpg",
  },
];

export default places;
